-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 16:02:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BankingSystemDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS BankingSystemDB;
CREATE DATABASE IF NOT EXISTS BankingSystemDB;
USE BankingSystemDB;
-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `customer_name` VARCHAR(45) NULL,
  `customer_id` INT NULL,
  `Postal_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Postal_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `date_birth` DATE NULL,
  `postal_code` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `postal_code_idx` (`postal_code` ASC) VISIBLE,
  CONSTRAINT `fk_postal_code`
    FOREIGN KEY (`postal_code`)
    REFERENCES `Address` (`Postal_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_number` TINYINT NOT NULL,
  `account_type` VARCHAR(45) NULL,
  `balance` DECIMAL NULL,
  PRIMARY KEY (`account_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransferFund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransferFund` ;

CREATE TABLE IF NOT EXISTS `TransferFund` (
  `customer_id` INT NOT NULL,
  `account_number` TINYINT NOT NULL,
  PRIMARY KEY (`customer_id`, `account_number`),
  INDEX `account_number_idx` (`account_number` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_number`
    FOREIGN KEY (`account_number`)
    REFERENCES `Account` (`account_number`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `manager_id` TINYINT(2) NOT NULL,
  `manager_name` VARCHAR(45) NULL,
  `start_date` TIMESTAMP NULL,
  `branch_id` TINYINT(4) NOT NULL,
  PRIMARY KEY (`manager_id`, `branch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Branch` ;

CREATE TABLE IF NOT EXISTS `Branch` (
  `branch_id` TINYINT(4) NOT NULL,
  `branch_name` VARCHAR(45) NULL,
  `branch_address` VARCHAR(45) NULL,
  `Manager_manager_id` TINYINT(2) NOT NULL,
  `Manager_branch_id` TINYINT(4) NOT NULL,
  PRIMARY KEY (`branch_id`, `Manager_manager_id`, `Manager_branch_id`),
  INDEX `fk_Branch_Manager1_idx` (`Manager_manager_id` ASC, `Manager_branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_Branch_Manager1`
    FOREIGN KEY (`Manager_manager_id` , `Manager_branch_id`)
    REFERENCES `Manager` (`manager_id` , `branch_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Service` ;

CREATE TABLE IF NOT EXISTS `Service` (
  `customer_id` INT NOT NULL,
  `branch_id` TINYINT(4) NOT NULL,
  PRIMARY KEY (`customer_id`, `branch_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Branch` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loan` ;

CREATE TABLE IF NOT EXISTS `Loan` (
  `loan_id` INT NOT NULL,
  `loan_type` VARCHAR(45) NULL,
  `loan_amount` DECIMAL NULL,
  PRIMARY KEY (`loan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LoanType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LoanType` ;

CREATE TABLE IF NOT EXISTS `LoanType` (
  `customer_id` INT NOT NULL,
  `loan_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `loan_id`),
  INDEX `loan_id_idx` (`loan_id` ASC) VISIBLE,
  CONSTRAINT `fk_loanType_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loantype_loan_id`
    FOREIGN KEY (`loan_id`)
    REFERENCES `Loan` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employee_id` INT NOT NULL,
  `employee_name` VARCHAR(45) NULL,
  `hire_date` DATE NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JobAssignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JobAssignment` ;

CREATE TABLE IF NOT EXISTS `JobAssignment` (
  `branch_id` TINYINT(4) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`branch_id`, `employee_id`),
  CONSTRAINT `branch_id`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Branch` (`branch_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CreditCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CreditCard` ;

CREATE TABLE IF NOT EXISTS `CreditCard` (
  `card_number` TINYINT(9) NOT NULL,
  `card_type` VARCHAR(45) NULL,
  `expiry_date` DATE NULL,
  PRIMARY KEY (`card_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Created`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Created` ;

CREATE TABLE IF NOT EXISTS `Created` (
  `card_number` TINYINT(9) NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`card_number`, `customer_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_number`
    FOREIGN KEY (`card_number`)
    REFERENCES `CreditCard` (`card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_id_num`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `transaction_id` TINYINT NOT NULL,
  `transaction_type` VARCHAR(45) NULL,
  `transaction_amount` DECIMAL NULL,
  `card_number` TINYINT(9) NOT NULL,
  `loan_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `card_number_idx` (`card_number` ASC) VISIBLE,
  INDEX `loan_id_idx` (`loan_id` ASC) VISIBLE,
  CONSTRAINT `card_number`
    FOREIGN KEY (`card_number`)
    REFERENCES `CreditCard` (`card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `loan_id`
    FOREIGN KEY (`loan_id`)
    REFERENCES `Loan` (`loan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM` ;

CREATE TABLE IF NOT EXISTS `ATM` (
  `atm_id` TINYINT NOT NULL,
  `atm_location` VARCHAR(45) NULL,
  `atm_installation` DATE NULL,
  `branch_id` TINYINT(4) NOT NULL,
  PRIMARY KEY (`atm_id`),
  INDEX `branch_id_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_branch_id_num`
    FOREIGN KEY (`branch_id`)
    REFERENCES `Branch` (`branch_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` TINYINT NOT NULL,
  `payment_method` VARCHAR(45) NULL,
  `payment_amount` DECIMAL NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check` ;

CREATE TABLE IF NOT EXISTS `Check` (
  `check_number` TINYINT(4) NOT NULL,
  `account_numbers` TINYINT NULL,
  `check_amount` DECIMAL NULL,
  `Payment_payment_id` TINYINT NOT NULL,
  PRIMARY KEY (`check_number`),
  INDEX `fk_Check_Payment1_idx` (`Payment_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Check_Payment1`
    FOREIGN KEY (`Payment_payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DebitCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DebitCard` ;

CREATE TABLE IF NOT EXISTS `DebitCard` (
  `debitcard_id` TINYINT NOT NULL,
  `card_holder_name` VARCHAR(45) NULL,
  `expir_date` TIMESTAMP NULL,
  PRIMARY KEY (`debitcard_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CreatedCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CreatedCard` ;

CREATE TABLE IF NOT EXISTS `CreatedCard` (
  `customer_id` INT NOT NULL,
  `debitcard_id` TINYINT NOT NULL,
  PRIMARY KEY (`customer_id`, `debitcard_id`),
  INDEX `debitcard_id_idx` (`debitcard_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_id_created_card`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_debitcard_id_created_card`
    FOREIGN KEY (`debitcard_id`)
    REFERENCES `DebitCard` (`debitcard_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DebitPayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DebitPayment` ;

CREATE TABLE IF NOT EXISTS `DebitPayment` (
  `debitcard_id` TINYINT NOT NULL,
  `payment_id` TINYINT NOT NULL,
  PRIMARY KEY (`debitcard_id`, `payment_id`),
  CONSTRAINT `fk_debitcard_id`
    FOREIGN KEY (`debitcard_id` )
    REFERENCES `DebitCard` (`debitcard_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_id`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
